---
title: Geef een ​​sprite in Scratch een nieuwe naam
hero_image: afbeeldingen / banner.png
description: Geef een ​​sprite in Scratch een nieuwe naam
listed: false
copyedit: true
steps:
  - 
    title: Geef een ​​sprite een nieuwe naam
