---
title: Palitan ang pangalan ng isang sprite sa Scratch
hero_image: mga imahe / banner.png
description: Palitan ang pangalan ng isang sprite sa Scratch
listed: false
copyedit: true
steps:
  - 
    title: Palitan ang pangalan ng isang sprite
