---
title: Cambiar el nombre de un objeto en Scratch
hero_image: images/banner.png
description: Cambiar el nombre de un objeto en Scratch
listed: false
copyedit: true
steps:
  - 
    title: Cambiar el nombre de un sprite
