---
title: Cambiar el nombre de un sprite en Scratch
hero_image: images/banner.png
description: Cambiar el nombre de un sprite en Scratch
listed: false
copyedit: true
steps:
  - title: Cambiar el nombre de un sprite
