---
title: Nevezz át egy szereplőt a Scratchben
hero_image: images/banner.png
description: Nevezz át egy szereplőt a Scratchben
listed: false
copyedit: true
steps:
  - 
    title: Nevezz át egy szereplőt
