---
title: Scratch'te bir kuklanın yeniden adlandırılması
hero_image: images/banner.png
description: Scratch'te bir kuklanın yeniden adlandırılması
listed: false
copyedit: true
steps:
  - 
    title: Bir kuklanın yeniden adlandırılması
